### ISSUE TITLE
window.postMessage is not ready right away because of WKUserScriptInjectionTime atDocumentEnd

### ISSUE THREAD

**Issue by henrylearn2rock** [CRAlpha/react-native-wkwebview#166] opened 2018-07-19 00:04 UTC
Version: 1.21
(iOS: 11.4)

`window.webkit.messageHandlers.reactNative.postMessage` works as documented, but `window.postMessage({message: 'hello!'})` throws Not enough arguments 

When I try `window.postMessage({message: 'hello!'}, '*')`, the message is not being sent to RN.

Thanks!

**Comment by henrylearn2rock** [comment] 2018-07-20 05:33
It works, but not right away.  
Looks like there is a delay similar to https://github.com/facebook/react-native/issues/11594

**Comment by shirakaba** [comment] 2018-07-20 09:44
> `window.postMessage({message: 'hello!'})` throws Not enough arguments

Indeed, it is required to specify the target origin: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

`window.postMessage(data)` is an alias for:

```js
function (data) {
    window.webkit.messageHandlers.reactNative.postMessage(data);
}
```

However, this alias is only set upon the `- (void)webView:(WKWebView *)webView didFinishNavigation:(__unused WKNavigation *)navigation` being set. So the whole webpage will need to be loaded before the `window.postMessage(data)` alias is available.

As a quick guess, you could try running the same aliasing code in an earlier part of the webpage loading lifecycle – in the new `injectJavaScript` prop:

```js
window.originalPostMessage = window.postMessage;
window.postMessage = function() {
    return window.webkit.messageHandlers.reactNative.postMessage.apply(window.webkit.messageHandlers.reactNative, arguments);
};
```

Disclaimer: there may well be a valid reason for this aliasing happening only after the page has been loaded; I haven't read the code in detail.

You could consider submitting a PR that moves the aliasing code to that earlier part of the webpage loading lifecycle if you could convincingly determine that there are no issues in doing so.

... Otherwise, just use the non-aliased `window.webkit.messageHandlers.reactNative.postMessage` method!

**Comment by henrylearn2rock** [comment] 2018-07-20 17:36
Looks like `WKUserScriptInjectionTime.atDocumentStart` would solve this?

ref: https://developer.apple.com/documentation/webkit/wkuserscript

**Comment by shirakaba** [comment] 2018-07-20 17:39
That's the webpage loading lifecycle event that I was referring to, yes. The `injectJavaScript` prop injects JavaScript upon that lifecycle event.

**Comment by henrylearn2rock** [comment] 2018-07-20 17:42
https://github.com/CRAlpha/react-native-wkwebview/blob/master/ios/RCTWKWebView/RCTWKWebView.m#L141

Looks like currently the `origin` param is being dropped?

**Comment by shirakaba** [comment] 2018-07-20 17:55
Yes. It seems that if `messagingEnabled` is `true`, then `postMessage(data, origin)` will be repurposed to simply run the function `window.webkit.messageHandlers.reactNative.postMessage(data)`. `origin` effectively becomes irrelevant, because the message is implicitly being posted to a certain message handler that isn't interested in it.

I'll be the first to say that I don't see why anyone would ever want to enable such behaviour (I dislike non-explicit behaviours), but I guess it's just a reproduction of what the `<WebView>` component does.

**Comment by insraq** [comment] 2018-07-20 18:13
Yes. This is added to be "compatible" with <WebView>. I don't like it either. But it helps people migrating from WebView.

**Comment by shirakaba** [comment] 2018-07-20 19:08
@insraq Do you support moving this declaration... :

```js
window.originalPostMessage = window.postMessage;
window.postMessage = function() {
    return window.webkit.messageHandlers.reactNative.postMessage.apply(window.webkit.messageHandlers.reactNative, arguments);
};
```

... to the `WKUserScriptInjectionTime.atDocumentStart` part of the lifecycle?

**Comment by shirakaba** [comment] 2018-07-21 11:54
@insraq Thank you for adding me as a collaborator!

@henrylearn2rock Are you confident to submit a PR for this, or would you prefer to leave it with me?

Looks like it might be as simple as changing the lines in `RCTWKWebView.m`:

```Obj-C
- (void)setupPostMessageScript {
  if (_messagingEnabled) {
    NSString *source=@"window.originalPostMessage = window.postMessage; window.postMessage = function (data) { window.webkit.messageHandlers.reactNative.postMessage(data); }";
    WKUserScript *script = [[WKUserScript alloc] initWithSource:source
                           injectionTime:WKUserScriptInjectionTimeAtDocumentEnd
                                               forMainFrameOnly:_injectedJavaScriptForMainFrameOnly];
    [_webView.configuration.userContentController addUserScript:script];
  }
}
```

... replacing `WKUserScriptInjectionTimeAtDocumentEnd` with `WKUserScriptInjectionTimeAtDocumentStart`.

Don't think `WKWebView.ios.js` needs changing.

@henrylearn2rock First, could you try making that one-line change I've mentioned above in your own install of this project (no need to fork the repo, for this initial experiment: just go into `YOUR_PROJECT/node_modules/react-native-wkwebview-reborn/ios/RCTWKWebView/RCTWKWebView.m`), change that one line, and run your ios app target in `YOUR_PROJECT.xcodeproj` again. Please report back about whether your issues are solved.

**Comment by henrylearn2rock** [comment] 2018-07-21 16:03
Good news, it works as expected.  After changing that line to `WKUserScriptInjectionTimeAtDocumentStart`
I tried `alert(window.postMessage.length)` right away in the JS and it shows 1, meaning it has already been overridden with the one expecting 1 argument.

@shirakaba I haven't cloned this repo, so pls go ahead! 👍 Thanks!

**Comment by shirakaba** [comment] 2018-07-21 16:33
I've started a PR for this at #167 . Note that I haven't tested anything on my end yet (not sure when I'll be free to do so yet).

@henrylearn2rock What props would I need to enter in order to test this? I haven't used this feature before. I see a reference to `messagingEnabled` in the source code, but the documentation doesn't mention it. Do I need to set that to `true` as well as setting the `onMessage` callback?

**Comment by henrylearn2rock** [comment] 2018-07-21 17:51
`onMessage` needs to have a callback function, then `messagingEnabled` will be set to true.

**Comment by shirakaba** [comment] 2018-07-28 19:05
Sorry for the delay. I lost a whole day testing `window.postMessage()`, and found that, whether the aliasing is configured to `.atDocumentStart` or `.atDocumentEnd`, my specific use-case was broken (issue #170). The use-case in question was the posting of messages to iframes (in fact, this is probably the original purpose of the `onMessage` API). This prevented me from assessing the PR itself.

You know, I wonder now whether the reason that the `postMessageScript` is set up `.atDocumentEnd` is so that any `window.postMessage` calls sent while a webpage is still loading (e.g. by the website-maker, not the React Native developer) will not break.

Anyway, regardless of the reasoning, I feel that we should maintain consistency with React Native core (wherein the aliasing is effectively configured to `.atDocumentEnd` because the configuration occurs [during the `UIWebView`'s `webViewDidFinishLoad` hook](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/React/Views/RCTWebView.m#L313)) until such time as they change it.

If you want it to be effectively available `.atDocumentStart`, then add this code to the `injectJavaScript` prop of your `<WKWebView>` component – it's a hook that runs upon `.atDocumentStart`:

```js
window.originalPostMessage = window.postMessage;
window.postMessage = function() {
    return window.webkit.messageHandlers.reactNative.postMessage.apply(window.webkit.messageHandlers.reactNative, arguments);
};
```

**Closed by shirakaba** 2018-07-28 19:05 UTC

**Comment by insraq** [comment] 2018-07-28 19:22
I think the reason why WebView injects this at the end of documents is that there're no other options. I don't see any problems moving this to the document start.

Regarding #170, I think we should de-couple the method override from onMessage callback - make it more explicit. I propose:

1. Move the code to document start
2. Do not override postMessage when there's an `onMessage` callback
3. Add a new prop: `overridePostMessage` that override postMessage.

**Comment by shirakaba** [comment] 2018-07-28 21:47
> I think we should de-couple the method override from onMessage callback

@insraq That all sounds reasonable if we're happy to diverge a little bit from the (to be frank, problematic) implementation of the native `<WebView>` component – e.g. see the documentation for the `onMessage` prop:

>      /**
>      * A function that is invoked when the webview calls `window.postMessage`.
>      * Setting this property will inject a `postMessage` global into your
>      * webview, but will still call pre-existing values of `postMessage`.
>      *
>      * `window.postMessage` accepts one argument, `data`, which will be
>      * available on the event object, `event.nativeEvent.data`. `data`
>      * must be a string.
>      */
>     onMessage: PropTypes.func

If I may draw your attention to PR #176, however, which would allow us to forego the addition of an `overridePostMessage` prop entirely...

Through this PR, we could furthermore move the code to `.atDocumentStart` without worrying about breaking websites that send `postMessage()` actions before the `<body>` has loaded, nor losing consistency with `<WebView>`.
